[project]
name = "odestimate"
version = "0.0.1"
dependencies = [
    "numpy",
    "torch",
    "scipy",
    "scikit-learn",
    "tqdm",
]

[project.optional-dependencies]
test = ["pytest", "matplotlib", "ipykernel", "ipywidgets"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
